<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PresidentResearchResource\Pages;
use App\Filament\Resources\PresidentResearchResource\RelationManagers;
use App\Models\PresidentResearch;
use App\Models\Research;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Actions\DeleteAction;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class PresidentResearchResource extends Resource
{
    protected static ?string $model = Research::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';
    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('college_id',auth()->user()->college_id); // TODO: Change the autogenerated stub
    }

    public static function canAccess(): bool
    {
        return auth()->user()->role_id==4; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')
                    ->sortable(),
                TextColumn::make('title')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('status')
                    ->alignCenter()
                    ->badge()
                    ->color(fn(string $state): string => match ($state) {
                        'progress' => 'info',
                        'under_review' => 'gray',
                        'under_evaluate' => 'warning',
                        'publish' => 'success',
                        'reject' => 'danger',
                    })
                    ->sortable(),
                TextColumn::make('marks')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('student.name')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('subject.name')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('college.name')
                    ->searchable()
                    ->sortable(),


            ])
            ->filters([
                SelectFilter::make('college_id')
                    ->relationship("college", "name"),
            ])
            ->actions([
                ViewAction::make('view')
                    ->button(),

                EditAction::make('edit')
                    ->button(),

                DeleteAction::make('delete')
                    ->button(),
                Tables\Actions\Action::make("files.download")
                    ->url(fn(Research $record) => route("files.download", $record))
                    ->button()
                    ->color("info")
                    ->disabled(fn(Research $record) => $record->status == "progress")
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPresidentResearch::route('/'),
            'create' => Pages\CreatePresidentResearch::route('/create'),
            'edit' => Pages\EditPresidentResearch::route('/{record}/edit'),
        ];
    }
}
