<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ResearchResource\Pages;
use App\Filament\Resources\ResearchResource\RelationManagers;
use App\Models\College;
use App\Models\Department;
use App\Models\File;
use App\Models\Research;
use App\Models\Subject;
use App\Models\User;
use Closure;
use Filament\Forms;
use Filament\Forms\Components\DateTimePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Forms\Get;
use Filament\Infolists\Infolist;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Actions\DeleteAction;
use Filament\Tables\Actions\EditAction;
use Filament\Tables\Actions\ViewAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use PHPUnit\Metadata\Group;
use function Laravel\Prompts\select;
use function PHPUnit\Framework\isEmpty;
use function PHPUnit\Framework\isNull;

class ResearchResource extends Resource
{
    protected static ?string $model = Research::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';
    protected static ?string $navigationGroup="Research";


    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->with(["student","teacher","administer","subject","college","files"]); // TODO: Change the autogenerated stub
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([

                Forms\Components\Group::make([
                    Forms\Components\Section::make("Research information")
                        ->schema([
                            TextInput::make("title")
                                ->string()
                                ->required(),
                            TextInput::make("description")
                                ->string()
                                ->required(),
                            TextInput::make("abstract")
                                ->string(),
                            FileUpload::make('research.files')
                                ->label('Research Documentation')

                                ->multiple()
                                ->preserveFilenames()
                                ->openable()
                                ->downloadable()
                                ->disk('public') // Ensure you're specifying the correct disk
// Temporarily store files here


                        ])->columns(2),
                    Forms\Components\Section::make("Student")
                        ->schema([
                            Forms\Components\Select::make("college_id")
                                ->options(College::all()->pluck("name", "id"))
                                ->reactive()
                                ->searchable()
                                ->required(),

                            Forms\Components\Select::make("subject_id")
                                ->options(fn(Get $get): Collection => Subject::query()
                                    ->when(isNull($get('college_id')), function ($query) use ($get) {
                                        return $query->where("college_id", $get('college_id'));
                                    })->pluck("name", "id")
                                )
                                ->reactive()
                                ->searchable()
                                ->required(),
                            Forms\Components\Select::make("student_id")
                                ->options(fn(Get $get): Collection => User::query()
                                    ->where("role_id", "=", 2)
                                    ->when(isNull($get('subject_id')), function ($query) use ($get) {

                                        return $query->where("subject_id", $get('subject_id'));

                                    })->pluck("name", "id")
                                )
                                ->required(),
                            DateTimePicker::make("prepared_at")
                                ->string()
                                ->required(),
                        ])->columns(2),
                    Forms\Components\Section::make("Supervisor")
                        ->schema([

                            Forms\Components\Group::make([
                                Forms\Components\Select::make("teacher_id")
                                    ->options(fn(Get $get): Collection => User::query()
                                        ->where("role_id", "=", 3)
                                        ->when(isNull($get('subject_id')), function ($query) use ($get) {

                                            return $query->where("subject_id", $get('subject_id'));

                                        })->pluck("name", "id")
                                    )
                                    ->required(),
                                TextInput::make("marks")
                                    ->minValue(0)
                                    ->integer()
                                    ->required(),
                                TextInput::make("comments")
                                    ->string()
                                    ->required(),
                            ]),
                        ]),
                    Forms\Components\Section::make("Administrator")
                        ->schema
                        ([
                                Forms\Components\Select::make("administer_id")
                                    ->label("Administrator")
                                    ->options(fn(Get $get): Collection => User::query()
                                        ->where("role_id", "=", 4)
                                        ->when(isNull($get('college_id')), function ($query) use ($get) {
                                            return $query
                                                ->where("college_id", $get('college_id'));
                                        })->pluck("name", "id")
                                    )
                                    ->required(),
                                DateTimePicker::make("administer_answered_at")
                                    ->label("Administrator_result")
                                    ->string()
                                    ->required(),

                            TextInput::make("plagiarism_percentage")
                                ->integer()
                                ->prefix(" % ")
                                ->maxValue(100)
                                ->minValue(0)
                                ->required(),

                            Forms\Components\Select::make("status")
                                ->options(["draft"=>"draft", "under_review"=>"under_review", "progress"=>"progress", "under_evaluate"=>"under_evaluate", "publish"=>"publish", "reject"=>"reject"])
                                ->required(),
                        ])->columns(2)

                ])->columnSpan(2),


            ])->columns(2);
    }
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')
                    ->sortable(),
                TextColumn::make('title')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('status')
                    ->alignCenter()
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'draft' => 'gray',
                        'under_review' => 'warning',
                        'progress' => 'info',
                        'under_evaluate' => 'warning',
                        'publish' => 'success',
                        'reject' => 'danger',
                    })
                    ->sortable(),
                TextColumn::make('marks')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('student.name')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('subject.name')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('college.name')
                    ->searchable()
                    ->sortable(),


            ])
            ->filters([
                //
            ])
            ->actions([
                ViewAction::make('view')
                    ->button(),

                EditAction::make('edit')
                    ->button(),

                DeleteAction::make('delete')
                    ->button(),
                Tables\Actions\Action::make("files.download")
                    ->url(fn (Research $record) => route("files.download", $record))
                    ->button()
                    ->color("info")
                    ->hidden(fn (Research $record) => $record->status=="draft"||$record->status=="under_review")
                ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }


    public static function getPages(): array
    {
        return [
            'index' => Pages\ListResearch::route('/'),
            'create' => Pages\CreateResearch::route('/create'),
            'edit' => Pages\EditResearch::route('/{record}/edit'),
        ];
    }
}
