<?php

namespace App\Filament\Resources\TeacherResearchResource\Pages;

use App\Filament\Resources\TeacherResearchResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CreateTeacherResearch extends CreateRecord
{
    protected static string $resource = TeacherResearchResource::class;
    protected function handleRecordCreation(array $data): Model
    {
        DB::beginTransaction();
        $data["teacher_id"]=auth()->id();
        $data["subject_id"]=auth()->user()["subject_id"];
        $data["college_id"]=auth()->user()["college_id"];
        $data["status"]="progress";
        $record =  static::getModel()::create($data);




        DB::commit();

        return $record; // TODO: Change the autogenerated stub
    }
}
